# Generated by Django 4.0.4 on 2022-05-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTask', models.CharField(max_length=50)),
                ('userCreate', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('alert5min', models.BooleanField(default=False)),
                ('alert', models.BooleanField(default=False)),
            ],
        ),
    ]
